project:
  type: website
  output-dir: docs

website:
  title: "Tahia Anan Dhira"

  navbar:
    left:
      - href: index.qmd
        text: Home

      - href: research.qmd
        text: Research

      - href: cv.qmd
        text: CV

      - href: visualizations.qmd
        text: Visualizations

      - href: code.qmd
        text: Code

      - href: interests.qmd
        text: Elsewhere

      - href: contact.qmd
        text: Contact

format:
  html:
    theme: cosmo
    css: styles.css
    toc: false
    title-block-banner: false