project:
  type: website
  output-dir: docs

resources:
  - CNAME
  - images
  - visualizations.js
  - TahiaAnanDhira_CV.pdf
  - Code_Sample_R.pdf
  - Code_Sample_Python.pdf
  - code_sample_STATA.pdf

website:
  title: "Tahia Anan Dhira"

  navbar:
    title: false

    left:
      - href: index.qmd
        text: Home

      - href: research.qmd
        text: Research

      - href: teaching.qmd
        text: Teaching

      - href: visualizations.qmd
        text: Visualizations

      - href: blog.qmd
        text: Blog

    right:
      - text: "Beyond Academia"
        menu:
          - href: photojournal.qmd
            text: Photo Journal

          - href: https://art.tahiaanandhira.com
            text: Paintings

format:
  html:
    theme: cosmo
    css: styles.css
    toc: false
    title-block-banner: false