project:
  type: website
  output-dir: docs

website:
  title: "Tahia Anan Dhira"
  site-url: https://tahiaanandhira.com

  navbar:
    left:
      - href: research.qmd
        text: Research

      - href: cv.qmd
        text: CV

      - href: visualizations.qmd
        text: Visualizations

      - href: code.qmd
        text: Code

      - href: https://art.tahiaanandhira.com
        text: Elsewhere

    right:
      - icon: envelope-fill
        href: mailto:dhiraanan3@gmail.com

      - icon: github
        href: https://github.com/TAD600

      - icon: linkedin
        href: https://www.linkedin.com/in/dhiraanan/

      - text: ORCID
        href: https://orcid.org/0000-0001-7403-9862

format:
  html:
    theme: cosmo
    css: styles.css
    toc: false
    title-block-banner: false