
---
title: "Code"
---

This page contains selected code snippets from my research projects. Full reproducible workflows are available on GitHub repositories.


```Stata code sample
import delimited "data/cleaned/panel_complete.csv", clear

* Summary statistics

unique dyad
unique year

* GDP transformations

gen sum_gdp_pc = log_gdp_pc_d + log_gdp_pc
gen abs_gdp_pc = abs(log_gdp_pc - log_gdp_pc_d)

* Landlocked indicator

gen landlock = (landlocked == 1 & landlocked_d == 1)
label variable landlock "1 both countries are landlocked, 0 any of them or both have seaports"

* Development classification

gen dev = (development == 1) + 2*(development_d == 1)
label variable dev "1 developing-developing, 2 developed-developing, 3 developing-developed, 4 developed-developed"

ssc install reghdfe

ssc install ppmlhdfe, replace


local outcomes unique reproducible noncultural_trade

foreach y of local outcomes {
    ppmlhdfe `y' sum_gdp_pc abs_gdp_pc rta contig comlang_off colony comcol log_dist landlock i.dev, ///
    a(year) vce(cluster dyad)
}

foreach y of local outcomes {
    ppmlhdfe `y' sum_gdp_pc abs_gdp_pc hysteresis_`y' ///
    rta contig comlang_off colony comcol log_dist landlock i.dev, ///
    a(year) vce(cluster dyad)
}

foreach y of local outcomes {
    ppmlhdfe `y' sum_gdp_pc abs_gdp_pc rta contig comlang_off colony comcol log_dist landlock i.dev, ///
    a(dyad year) vce(cluster dyad)
}

egen exp_year = group(iso_o year)
egen imp_year = group(iso_d year)

foreach y of local outcomes {
    ppmlhdfe `y' sum_gdp_pc abs_gdp_pc hysteresis_`y' ///
    rta contig comlang_off colony comcol log_dist landlock i.dev, ///
    a(exp_year imp_year) vce(cluster dyad)
}

local outcomes unique reproducible noncultural_trade

foreach y of local outcomes {
    ppmlhdfe `y' sum_gdp_pc abs_gdp_pc hysteresis_`y' ///
    rta contig comlang_off colony comcol log_dist landlock i.dev , ///
    a(dyad exp_year imp_year) vce(cluster dyad) 
    
}


